openapi: 3.0.0
info:
  version: "2.9.0"
  title: GovPay - API Ragioneria
  contact:
    name: GitHub Project Page
    url: 'https://github.com/link-it/GovPay/'
  license:
    name: GPL
    url: 'https://github.com/link-it/GovPay/blob/master/LICENSE'
servers:
  - url: /govpay/backend/api/ragioneria/rs/basic/v2/
tags:
  - name: Rendicontazioni
    description: Consultazione delle rendicontazioni emesse da pagoPA
  - name: Riscossioni
    description: Consultazione delle riscossioni eseguite da pagoPA
  - name: Riconciliazioni
    description: Esecuzione e consultazione delle riconciliazioni
  - name: Utenti
    description: Anagrafica degli Utenti
security:
  - basicAuth: []    
paths:
  '/flussiRendicontazione':
    get:
      summary: Elenco dei flussi di rendicontazione acquisite da pagoPa
      operationId: findFlussiRendicontazione
      tags:
        - Rendicontazioni
      parameters:
        - $ref: '#/components/parameters/pagina'
        - $ref: '#/components/parameters/risultatiPerPagina'
        - $ref: '#/components/parameters/campi'
        - $ref: '#/components/parameters/ordinamento'
        - $ref: '#/components/parameters/idDominio'
        - $ref: '#/components/parameters/dataDa'
        - $ref: '#/components/parameters/dataA'
        - $ref: '#/components/parameters/statoFlussoRendicontazione'
        - $ref: '#/components/parameters/metadatiPaginazione'
        - $ref: '#/components/parameters/maxRisultati'
        - $ref: '#/components/parameters/iuv'
      responses:
        '200':
          description: Lista dei flussi rendicontazione
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlussiRendicontazione'
        '400':
          $ref: '#/components/responses/400BadRequest'                
        '401':
          $ref: '#/components/responses/401NotAuthenticated'
        '403':
          $ref: '#/components/responses/403NotAuthorized'
        '500':
          $ref: '#/components/responses/500ServiceUnavailable'  
  '/flussiRendicontazione/{idFlusso}':
    get:
      summary: Acquisizione di un flusso di rendicontazione
      operationId: getFlussoRendicontazione
      tags:
        - Rendicontazioni
      parameters:
        - in: path
          name: idFlusso
          description: Identificativo del flusso di rendicontazione
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Dettaglio della rendicontazione
          content:
            application/xml:
              schema:
                type: string
                example: xml del flusso di rendicontazione
            application/json:
              schema:
                $ref: '#/components/schemas/FlussoRendicontazione'
        '401':
          $ref: '#/components/responses/401NotAuthenticated'
        '403':
          $ref: '#/components/responses/403NotAuthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500ServiceUnavailable'  
  '/flussiRendicontazione/{idFlusso}/{dataOraFlusso}':
    get:
      summary: Acquisizione di un flusso di rendicontazione
      operationId: getFlussoRendicontazioneByIdEData
      tags:
        - Rendicontazioni
      parameters:
        - in: path
          name: idFlusso
          description: Identificativo del flusso di rendicontazione
          required: true
          schema:
            type: string
        - in: path
          name: dataOraFlusso
          description: Data di emissione del flusso
          required: true
          schema:
            type: string
            format: date-time
      responses:
        '201':
          description: Dettaglio della rendicontazione
          content:
            application/xml:
              schema:
                type: string
                example: xml del flusso di rendicontazione
            application/json:
              schema:
                $ref: '#/components/schemas/FlussoRendicontazione'
        '401':
          $ref: '#/components/responses/401NotAuthenticated'
        '403':
          $ref: '#/components/responses/403NotAuthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500ServiceUnavailable'
  '/riconciliazioni':
    get:
      summary: Elenco dei movimenti di cassa riconciliati
      operationId: findRiconciliazioni
      tags:
        - Riconciliazioni
      parameters:
        - $ref: '#/components/parameters/pagina'
        - $ref: '#/components/parameters/risultatiPerPagina'
        - $ref: '#/components/parameters/campi'
        - $ref: '#/components/parameters/ordinamento'
        - $ref: '#/components/parameters/idDominio'
        - $ref: '#/components/parameters/dataDa'
        - $ref: '#/components/parameters/dataA'
        - $ref: '#/components/parameters/metadatiPaginazione'
        - $ref: '#/components/parameters/maxRisultati'
      responses:
        '200':
          description: Dettaglio dell'incasso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Riconciliazioni'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401NotAuthenticated'
        '403':
          $ref: '#/components/responses/403NotAuthorized'
        '500':
          $ref: '#/components/responses/500ServiceUnavailable'        
  '/riconciliazioni/{idDominio}':
    post:
      summary: Riconciliazione di un movimento di cassa
      operationId: addRiconciliazione
      tags:
        - Riconciliazioni
      parameters:
        - in: path
          name: idDominio
          description: Identificativo del creditore
          required: true
          schema:
            type: string    
            pattern: '(^([0-9]){11}$)'
        - $ref: '#/components/parameters/idFlussoCaseInsensitive'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NuovaRiconciliazione'
      responses:
        '201':
          description: Movimento riconciliato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Riconciliazione'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401NotAuthenticated'
        '403':
          $ref: '#/components/responses/403NotAuthorized'
        '500':
          $ref: '#/components/responses/500ServiceUnavailable'          
  '/riconciliazioni/{idDominio}/{idIncasso}':
    get:
      summary: Dettaglio di un movimento di cassa riconciliato
      operationId: getRiconciliazione
      tags:
        - Riconciliazioni
      parameters:
        - in: path
          name: idDominio
          description: Identificativo del creditore
          required: true
          schema:
            type: string  
            pattern: '(^([0-9]){11}$)'
        - in: path
          name: idIncasso
          description: Identificativo dell'idFlusso o iuv, a seconda della modalita di riversamento
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/tipiRiscossioneRiconciliazione'
      responses:
        '200':
          description: Dettaglio dell'incasso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Riconciliazione'
        '401':
          $ref: '#/components/responses/401NotAuthenticated'
        '403':
          $ref: '#/components/responses/403NotAuthorized'
        '404':
          $ref: '#/components/responses/404NotFound'
        '500':
          $ref: '#/components/responses/500ServiceUnavailable'        
  '/riscossioni':
    get:
      summary: Elenco degli importi riscossi o stornati
      operationId: findRiscossioni
      tags:
        - Riscossioni
      parameters:
        - $ref: '#/components/parameters/pagina'
        - $ref: '#/components/parameters/risultatiPerPagina'
        - $ref: '#/components/parameters/campi'
        - $ref: '#/components/parameters/ordinamento'
        - $ref: '#/components/parameters/idDominio'
        - $ref: '#/components/parameters/dataDa'
        - $ref: '#/components/parameters/dataA'
        - $ref: '#/components/parameters/tipiRiscossione'   
        - $ref: '#/components/parameters/metadatiPaginazione'
        - $ref: '#/components/parameters/maxRisultati'
      responses:
        '200':
          description: Dettaglio della riscossione
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Riscossioni'
        '400':
          $ref: '#/components/responses/400BadRequest'                  
        '401':
          $ref: '#/components/responses/401NotAuthenticated'
        '403':
          $ref: '#/components/responses/403NotAuthorized'
        '500':
          $ref: '#/components/responses/500ServiceUnavailable'           
  '/riscossioni/{idDominio}/{iuv}/{iur}/{indice}':
    get:
      summary: Dettaglio di una riscossione
      operationId: getRiscossione
      tags:
        - Riscossioni
      parameters:
        - in: path
          name: idDominio
          description: Codice fiscale del dominio beneficiario
          required: true
          schema:
            type: string
            pattern: '(^([0-9]){11}$)'
        - in: path
          name: iuv
          description: Identificativo univoco di versamento
          required: true
          schema:
            type: string
        - in: path
          name: iur
          description: Identificativo univoco di riscossione
          required: true
          schema:
            type: string
        - in: path
          name: indice
          description: Identificativo univoco di riscossione
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 5
      responses:
        '200':
          description: Dettaglio della riscossione
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Riscossione'
        '401':
          $ref: '#/components/responses/401NotAuthenticated'
        '403':
          $ref: '#/components/responses/403NotAuthorized'
        '404':
          $ref: '#/components/responses/400BadRequest'
        '500':
          $ref: '#/components/responses/500ServiceUnavailable'            
  '/profilo':
    get:
      summary: Elenco delle acl associate all'utenza chiamante
      tags:
        - Utenti
      operationId: getProfilo
      responses:
        '200':
          description: Autorizzazioni dell'utenza chiamante
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Profilo'
        '401':
          $ref: '#/components/responses/401NotAuthenticated'
        '500':
          $ref: '#/components/responses/500ServiceUnavailable'      
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  parameters:
    idDominio:
      name: idDominio
      in: query
      description: Identificativo del dominio dell'ente
      required: false
      schema:
        type: string
    idFlussoCaseInsensitive:
      in: query
      name: idFlussoCaseInsensitive
      description: Indica se effettuare la ricerca per Identificativo flusso in modalita' case insensitive
      required: false
      schema:
        type: boolean
    iuv:
      name: iuv
      in: query
      description: Identificativo del versamento
      required: false
      schema:
        type: string
    ccp:
      name: ccp
      in: query
      description: Codice contesto pagamento
      required: false
      schema:
        type: string
    dataDa:
      name: dataDa
      in: query
      description: Inizio della finestra temporale di osservazione
      required: false
      schema:
        type: string  
        format: date-time     
    dataA:
      name: dataA
      in: query
      description: Fine della finestra temporale di osservazione
      required: false
      schema:
        type: string  
        format: date-time     
    direzione:
      name: direzione
      in: query
      description: Identificativo della direzione interna all'ente creditore
      required: false
      schema:
        type: string
        example: Direzione ABC
    divisione:
      name: divisione
      in: query
      description: Identificativo della divisione interna all'ente creditore
      required: false
      schema:
        type: string
        example: Divisione001               
    campi:
      name: campi
      in: query
      description: Fields to retrieve
      required: false
      schema:
        type: string
    idA2A:
      name: idA2A
      in: query
      description: Identificativo del gestionale ente
      required: false
      schema:
        type: string
    idPendenza:
      name: idPendenza
      in: query
      description: Identificativo della pendenza nel gestionale ente
      required: false
      schema:
        type: string
    idPagamento:
      name: idPagamento
      in: query
      description: Identificativo della richiesta di pagamento
      required: false
      schema:
        type: string
      example: 'c8be909b-2feb-4ffa-8f98-704462abbd1d'  
    maxRisultati:
      name: maxRisultati
      in: query
      description: >-
            Indica se il servizio deve impostare o meno il limite sul calcolo del numero di risultati
      required: false
      schema:
        type: boolean
        default: true
      example: true
    metadatiPaginazione:
      name: metadatiPaginazione
      in: query
      description: >- 
              Indica se il servizio calcola e valorizza i dati di paginazione o meno
      required: false
      schema:
        type: boolean
        default: true
      example: true
    ordinamento:
      name: ordinamento
      in: query
      description: Sorting order
      required: false
      schema:
        type: string
    pagina:
      name: pagina
      in: query
      description: Numero di pagina di risultato
      required: false
      schema:
        $ref: '#/components/schemas/Pagina'        
    risultatiPerPagina:
      name: risultatiPerPagina
      in: query
      description: How many items to return at one time (max 100)
      required: false
      schema:
        type: integer
        default: 25
        maximum: 200
    statoFlussoRendicontazione:
      name: statoFlussoRendicontazione
      in: query
      description: Stato del flusso di rendicontazione
      required: false
      schema:
        $ref: '#/components/schemas/StatoFlussoRendicontazione'
    tipiRiscossione:
      in: query
      name: tipo
      description: Tipologia della riscossione (default [ENTRATA, MBT] )
      required: false
      schema:
        type: array
        items:
          $ref: '#/components/schemas/TipoRiscossione'
    tipiRiscossioneRiconciliazione:
      in: query
      name: riscossioni.tipo
      description: Tipologia della riscossione (default [ENTRATA, MBT] )
      required: false
      schema:
        type: array
        items:
          $ref: '#/components/schemas/TipoRiscossione'
    tipoRiscossione:
      name: tipoRiscossione
      in: query
      description: Tipo di riscossione
      required: false
      schema:
        $ref: '#/components/schemas/TipoRiscossione'
  headers:
    # Headers conform to http://zalando.github.io/restful-api-guidelines/index.html#132
    X-RateLimit-Limit:
      description: The number of allowed requests in the current period
      schema:
        type: integer
        format: int32
    X-RateLimit-Remaining:
      description: The number of remaining requests in the current period
      schema:
        type: integer
        format: int32
    X-RateLimit-Reset:
      description: The number of seconds left in the current period
      schema:
        type: integer
        format: int32
    Retry-After:
      description: Retry contacting the endpoint *at least* after seconds. See https://tools.ietf.org/html/rfc7231#section-7.1.3
      schema:
        type: integer
        format: int32
  responses:
    '400BadRequest':
      description: Richiesta non correttamente formata
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FaultBean'
          example:
            categoria: RICHIESTA
            codice: 00001
            descrizione: Messaggio di richiesta non valido
            dettaglio: Codice Avviso non conforme alle specifiche pagoPA
    '401NotAuthenticated':
      description: Richiesta non autenticata
    '403NotAuthorized':
      description: Richiesta non autorizzata
    '404NotFound':
      description: Risorsa inesistente
    '500ServiceUnavailable':
      description: Servizio non disponibile
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FaultBean'
          example:
            categoria: INTERNO
            codice: INTERNO
            descrizione: Servizio non disponibile
  schemas:
    Acl:
      type: object
      required:
        - servizio
        - autorizzazioni
      properties:
        ruolo:
          type: string
          description: ruolo a cui si applica l'acl
          example: Operatore
        principal:
          type: string
          description: principal a cui si applica l'acl
          example: user001
        servizio:
          $ref: "#/components/schemas/TipoServizio"
        autorizzazioni:
          $ref: "#/components/schemas/TipoAutorizzazione"  
    Contabilita:
      type: object
      properties:
        quote:
          type: array
          items: 
            $ref: '#/components/schemas/QuotaContabilita'
        proprietaCustom:
          type: object
          description: Dati specifici del gestionale di contabilità
    Dominio:
      type: object
      required:
        - idDominio
        - ragioneSociale
      properties:
        idDominio:
          type: string
          description: Codice fiscale
          example: 01234567890
          minLength: 1
          maxLength: 35          
        ragioneSociale:
          type: string
          description: Ragione sociale
          example: Ufficio due
          minLength: 1
          maxLength: 70
    FaultBean:
      type: object
      required:
        - categoria
        - codice
        - descrizione
      properties:
        categoria:
          type: string
          description: >-
            Categoria dell'errore riscontrato:
             * `AUTORIZZAZIONE` - Operazione non autorizzata
             * `RICHIESTA` - Richiesta non valida
             * `OPERAZIONE` - Operazione non eseguibile
             * `PAGOPA` - Errore da PagoPA
             * `EC` - Errore da Ente Creditore
             * `INTERNO` - Errore interno
          enum:
            - AUTORIZZAZIONE
            - RICHIESTA
            - OPERAZIONE
            - PAGOPA
            - EC
            - INTERNO
        codice:
          type: string
          description: Codice di errore
        descrizione:
          type: string
          description: Descrizione dell'errore
        dettaglio:
          type: string
          description: Descrizione aggiuntiva         
    FlussiRendicontazione:
      type: object
      allOf:
        - $ref: '#/components/schemas/Lista' 
        - type: object
          properties:
            risultati:
              type: array
              items: 
                $ref: '#/components/schemas/FlussoRendicontazioneIndex'                 
    FlussoRendicontazione:
      type: object
      allOf:
        - $ref: '#/components/schemas/FlussoRendicontazioneIndex'
        - type: object
          properties:
            rendicontazioni:
              type: array
              items:
                $ref: '#/components/schemas/Rendicontazione'              
    FlussoRendicontazioneIndex:
      type: object
      required:
        - idFlusso
        - dataFlusso
        - trn
        - dataRegolamento
        - idPsp
        - idDominio
        - numeroPagamenti
        - importoTotale
        - stato
      properties:
        idFlusso:
          type: string
          description: identificativo del flusso di rendicontazione
          example: 2017-11-21GovPAYPsp1-10:27:27.903
        dataFlusso:
          type: string
          format: date-time
          description: Data di emissione del flusso
          example: '2020-12-31 10:27:27.903'
        trn:
          type: string
          description: Identificativo dell'operazione di riversamento assegnato dal psp debitore
          example: 'idriversamento12345'
        dataRegolamento:
          type: string
          format: date-time
          description: Data dell'operazione di riversamento fondi
          example: '2020-12-31 10:27:27.903'        
        idPsp:
          type: string
          description: Identificativo dell'istituto mittente
          example: 'ABI-12345' 
        bicRiversamento:
          type: string
          description: Codice Bic della banca che ha generato il riversamento
          example: 'BIC-12345' 
        idDominio:
          type: string
          description: Identificativo dominio destinatario
          example: '01234567890' 
        numeroPagamenti:
          type: number
          description: numero di pagamenti oggetto della rendicontazione
          example: 3
        importoTotale:
          type: number
          description: somma degli importi rendicontati
          format: double
          example: 100.01      
        stato:
          $ref: '#/components/schemas/StatoFlussoRendicontazione'
        segnalazioni:
          type: array
          items:
            $ref: '#/components/schemas/Segnalazione'
    Limit:     
      type: integer
      format: int32
      default: 25
      maximum: 100
      minimum: 0      
    Lista:
      type: object
      properties:
        numRisultati:
          type: number
          format: integer
          example: '100'
        numPagine:
          type: number
          format: integer
          example: '4'
        risultatiPerPagina:
          type: number
          format: integer
          example: '25'
        pagina:
          type: number
          format: integer
          example: '1'
        prossimiRisultati:
          type: string
          format: integer
          example: '/risorsa?pagina=2' 
    NuovaRiconciliazione:
      allOf:
        - type: object
          required:
            - importo
            - sct
          properties:
            importo:
              type: number
              example: 100.01
            dataValuta:
              type: string
              format: date
              description: Data di valuta dell'incasso
              example: '2020-12-31'
            dataContabile:
              type: string
              format: date
              description: Data di contabile dell'incasso
              example: '2020-12-31'
            contoAccredito:
              type: string
              description: Identificativo del conto di tesoreria su cui sono stati incassati i fondi
              example: IT60X0542811101000000123456
            sct:
              type: string
              description: Identificativo Sepa Credit Transfer
              example: 2017-01-01ABI00000011234
        - oneOf:
          - description: Causale dell'operazione di riversamento dal PSP alla Banca Tesoriera.
            type: object
            required:
              - causale
            properties:
              causale:
                type: string
                example: /PUR/LGPE-RIVERSAMENTO/URI/2017-01-01ABI00000011234
          - description: Identificativo univoco di riscossione.
            type: object
            required:
              - iuv
            properties:
              iuv:
                type: string
                example: RF23567483937849450550875
          - description: Identificativo del flusso di rendicontazione.
            type: object
            required:
              - idFlusso
            properties:
              idFlusso:
                type: string
                example: 2017-11-21GovPAYPsp1-10:27:27.903
    Offset:
      type: integer
      format: int32
      default: 0
      minimum: 0    
    Pagina:
      type: integer
      default: 1
    Pendenza:
      type: object
      description: Dati della pendenza
      required:
        - idA2A
        - idPendenza
        - dataCaricamento
      properties:
        idA2A:
          type: string
          description: Identificativo del gestionale responsabile della pendenza
          example: A2A-12345
        idPendenza:
          type: string
          description: Identificativo della pendenza nel gestionale responsabile
          example: abcdef12345
        idDominio:
          type: string
          description: Identificativo del dominio creditore
          example: 1234567890
        idUnitaOperativa:
          type: string
          description: Identificativo dell'unita' operativa
          example: UO33132
        idTipoPendenza:
          type: string
          description: Identificativo della tipologia pendenza
          example: IMU
        causale:
          type: string
          description: Descrizione da inserire nell'avviso di pagamento
          example: 'Sanzione CdS n. abc00000'
          maxLength: 140     
        dataCaricamento:
          type: string
          format: date
          description: Data di emissione della pendenza
          example: '2010-12-31'
        dataValidita:
          type: string
          format: date
          description: Data di validita dei dati della pendenza, decorsa la quale la pendenza può subire variazioni.
          example: '2019-12-31'
        dataScadenza:
          type: string
          format: date
          description: Data di scadenza della pendenza, decorsa la quale non è più pagabile.
          example: '2020-12-31'
        annoRiferimento:
          type: number
          description: Anno di riferimento della pendenza
          example: 2020
        cartellaPagamento:
          type: string
          description: Identificativo della cartella di pagamento a cui afferisce la pendenza
          example: ABC00000001
        datiAllegati:
          type: object
          description: Dati applicativi allegati dal gestionale secondo un formato proprietario.
        tassonomia:
          type: string
          description: Macro categoria della pendenza secondo la classificazione del creditore
          example: Sanzioni
        tassonomiaAvviso:
          $ref: '#/components/schemas/TassonomiaAvviso'
        direzione:
          type: string
          description: Identificativo della direzione interna all'ente creditore
          example: Direzione ABC
        divisione:
          type: string
          description: Identificativo della divisione interna all'ente creditore
          example: Divisione001
        UUID:
          type: string
          description: Parametro di randomizzazione delle URL di pagamento statiche
    Profilo:
      type: object
      required: 
        - nome
        - domini
        - tipiPendenza
        - acl
      properties:
        nome:
          type: string
          description: Nome o principal dell'utenza
        domini:
          type: array
          description: domini su cui e' abilitato ad operare
          items: 
            $ref: '#/components/schemas/Dominio'
        tipiPendenza:
          type: array
          description: tipologie di pendenza su cui e' abilitato ad operare
          items:
            $ref: '#/components/schemas/TipoPendenza'
        acl:
          type: array
          items:
            $ref: '#/components/schemas/Acl'
        anagrafica:
          $ref: '#/components/schemas/Soggetto'
        identityData:
          type: object 
    QuotaContabilita:
      type: object
      required:
        - capitolo
        - annoEsercizio
        - importo
      properties:
        capitolo:
          type: string
          description: Codice del capitolo
          maxLength: 64
        annoEsercizio:
          type: number
          description: Anno di esercizio
          example: 2020
        importo:
          type: number
          description: Importo della voce di contabilita'
          example: 10.01
        accertamento:
          type: string
          description: Codice dell’accertamento
          maxLength: 64        
        proprietaCustom:
          type: object
          description: Dati specifici del gestionale di contabilità
        titolo:
          type: string
          description: Classificazione delle entrate in bilancio
          maxLength: 64
          example: 'titolo'
        tipologia:
          type: string
          description: Classificazione delle entrate in bilancio
          maxLength: 64
          example: 'tipologia'
        categoria:
          type: string
          description: Classificazione delle entrate in bilancio
          maxLength: 64
          example: 'categoria'
        articolo:
          type: string
          description: Classificazione delle entrate in bilancio
          maxLength: 64
          example: 'articolo'
    Rendicontazione:
      type: object
      required:
        - iuv
        - iur
        - indice
        - importo
        - esito
        - data
      properties:
        iuv:
          type: string
          description: Identificativo univoco di versamento
          example: 'RF23567483937849450550875'
        iur:
          type: string
          description: Identificativo univoco di riscossione
          example: '1234acdc'
        indice:
          type: number
          description: Indice dell'occorrenza del pagamento all’interno della struttura datiSingoloPagamento della Ricevuta Telematica.
          example: 1          
        importo:
          type: number
          description: Importo rendicontato. 
          example: 10.01
        esito:
          type: number
          description: >
            Codice di esito dell'operazione rendicontata
             * 0 = Pagamento eseguito
             * 3 = Pagamento revocato
             * 9 = Pagamento eseguito in assenza di RPT
          example: 0
        data:
          type: string
          format: date
          description: Data di esito
          example: '2018-12-31'
        segnalazioni:
          type: array
          items:
            $ref: '#/components/schemas/Segnalazione'
        riscossione:
          $ref: '#/components/schemas/RiscossioneIndex'
    Riconciliazione:
      type: object
      allOf:
        - $ref: '#/components/schemas/RiconciliazioneIndex' 
        - type: object
          properties: 
            riscossioni:
              type: array
              items: 
                $ref: '#/components/schemas/RiscossioneIndex' 
    RiconciliazioneIndex:
      type: object
      allOf:
        - $ref: '#/components/schemas/NuovaRiconciliazione' 
        - type: object
          required:
            - idDominio
            - idRiconciliazione
          properties:
            idDominio:
              type: string
              description: Identificativo ente creditore
              example: 01234567890
            idRiconciliazione:
              type: string
              description: Identificativo della riconciliazione assegnato da GovPay
              example: '12345'
    Riconciliazioni:
      type: object
      allOf:
        - $ref: '#/components/schemas/Lista' 
        - type: object
          properties:
            risultati:
              type: array
              items: 
                $ref: '#/components/schemas/RiconciliazioneIndex'          
    Riscossione:
      type: object
      allOf:
        - $ref: '#/components/schemas/RiscossioneIndex'
        - type: object
          properties:
            rt:
              type: object
              description: "Rt inviata da PagoPa. {http://www.digitpa.gov.it/schemas/2011/Pagamenti/} ctRicevutaTelematica"  
              example:
                versioneOggetto: "6.2.0"
                dominio:
                  identificativoDominio: "01234567890"
                  identificativoStazioneRichiedente: "99999999999_02"
                identificativoMessaggioRicevuta: "bc88bcd7fc2e479d87ae0a1913d9c31c"
                dataOraMessaggioRicevuta: "2018-12-31T12:53:49"
                riferimentoMessaggioRichiesta: "bc88bcd7fc2e479d87ae0a1913d9c31c"
                riferimentoDataRichiesta: "2018-12-31"
                istitutoAttestante:
                  identificativoUnivocoAttestante:
                    tipoIdentificativoUnivoco: "A"
                    codiceIdentificativoUnivoco: "99999"
                  denominazioneAttestante: "Banco di Ponzi S.p.A."
                  codiceUnitOperAttestante: null    
                  denomUnitOperAttestante: null    
                  indirizzoAttestante: null    
                  civicoAttestante: null    
                  capAttestante: null    
                  localitaAttestante: null    
                  provinciaAttestante: null
                  nazioneAttestante: null
                enteBeneficiario:
                  identificativoUnivocoBeneficiario:
                    tipoIdentificativoUnivoco: "G"
                    codiceIdentificativoUnivoco: "01234567890"
                  denominazioneBeneficiario: "Ente Creditore"
                  codiceUnitOperBeneficiario: null
                  denomUnitOperBeneficiario: null
                  indirizzoBeneficiario: "Piazza della Vittoria"
                  civicoBeneficiario: "1A"
                  capBeneficiario: "00000"
                  localitaBeneficiario: "Roma"
                  provinciaBeneficiario: "RO"
                  nazioneBeneficiario: "IT"
                soggettoVersante:
                  identificativoUnivocoVersante: 
                    tipoIdentificativoUnivoco: "F"
                    codiceIdentificativoUnivoco: "BNCGLO30A01H501I"
                  anagraficaVersante: "Giulio Bianchi"
                  indirizzoVersante: null 
                  civicoVersante: null
                  capVersante: null
                  localitaVersante: null
                  provinciaVersante: null
                  nazioneVersante: null
                  e-mailVersante: null
                soggettoPagatore: 
                  identificativoUnivocoPagatore:
                    tipoIdentificativoUnivoco: "F"
                    codiceIdentificativoUnivoco: "RSSMRA30A01H501I"
                  anagraficaPagatore: "Mario Rossi"
                  indirizzoPagatore: "Piazza della Vittoria"
                  civicoPagatore: "10/A"
                  capPagatore: "00000"
                  localitaPagatore: "Roma"
                  provinciaPagatore: "Roma"
                  nazionePagatore: "IT"
                  e-mailPagatore: "mario.rossi@host.eu"
                datiPagamento:
                  codiceEsitoPagamento: "1"
                  importoTotalePagato: "0.00"
                  identificativoUnivocoVersamento: "154340602921782"
                  CodiceContestoPagamento: "281120181253443049"
                  datiSingoloPagamento:
                    - singoloImportoPagato: "0.00"
                      esitoSingoloPagamento: "Conto insufficiente"
                      dataEsitoSingoloPagamento: "2018-11-28"
                      identificativoUnivocoRiscossione: "n/a"
                      causaleVersamento: "/RFB/154340602921782/45.01/TXT/Pagamento servizi"
                      datiSpecificiRiscossione: "9/SERVIZIO_1A"
                      commissioniApplicatePSP: null
                      allegatoRicevuta: null    
    RiscossioneIndex:
      type: object
      required:
        - dominio
        - iuv
        - iur
        - indice
        - tipo
        - importo
        - data
      properties:
        dominio:
          $ref: '#/components/schemas/Dominio'
        iuv:
          type: string
          description: Identificativo univoco di versamento
          example: RF23567483937849450550875
        iur:
          type: string
          description: Identificativo univoco di riscossione.
          example: '1234acdc'
        indice:
          type: number
          description: indice posizionale della voce pendenza riscossa
          example: 1
        stato:
          $ref: '#/components/schemas/StatoRiscossione'
        tipo:
          $ref: '#/components/schemas/TipoRiscossione'
        importo:
          type: number
          description: >-
            Importo riscosso. 
          example: 10.01
        data:
          type: string
          format: date
          description: Data di esecuzione della riscossione
          example: '2020-12-31'
        vocePendenza:
          $ref: '#/components/schemas/VocePendenza'       
        riconciliazione:
          type: string
          description: Riferimento all'operazione di riconciliazione, se avvenuta
          example: "/riconciliazioni/01234567890/2017-01-01ABI00000011234"   
    Riscossioni:
      type: object
      allOf:
        - $ref: '#/components/schemas/Lista' 
        - type: object
          properties:
            risultati:
              type: array
              items: 
                $ref: '#/components/schemas/RiscossioneIndex'                                       
    Segnalazione:
      type: object
      required:
        - codice
        - descrizione
      properties:
        data:
          type: string
          format: date-time
          example: '2018-12-31T12:53:49'
        codice:
          type: string
          example: '0013'
        descrizione:
          type: string   
          example: 'Pagamento rendicontato senza RPT'
        dettaglio:
          type: string
          example: 'Acquisita rendicontazione senza RPT nel flusso ABC-1234-DEFG'             
    Soggetto:
      description: dati anagrafici di un versante o pagatore.
      type: object
      required:
        - tipo
        - identificativo
      properties:
        tipo:
          $ref: "#/components/schemas/TipoSoggetto"
        identificativo:
          description: codice fiscale o partita iva del soggetto
          type: string
          example: RSSMRA30A01H501I
          minLength: 1
          maxLength: 35
        anagrafica:
          description: nome e cognome o altra ragione sociale del soggetto
          type: string
          example: Mario Rossi
          minLength: 1
          maxLength: 70
        indirizzo:
          type: string
          example: Piazza della Vittoria
          minLength: 1
          maxLength: 70
        civico:
          type: string
          example: 10/A
          minLength: 1
          maxLength: 16
        cap:
          type: string
          example: 00000
          minLength: 1
          maxLength: 16
        localita:
          type: string
          example: Roma
          minLength: 1
          maxLength: 35
        provincia:
          type: string
          example: Roma
          minLength: 1
          maxLength: 35
        nazione:
          type: string
          example: IT
          pattern: "[A-Z]{2,2}"
        email:
          type: string
          example: mario.rossi@host.eu
          pattern: "[A-Za-z0-9_]+([\\-\\+\\.'][A-Za-z0-9_]+)*@[A-Za-z0-9_]+([\\-\\.][A-Za-z0-9_]+)*\\.[A-Za-z0-9_]+([\\-\\.][A-Za-z0-9_]+)*"
        cellulare:
          type: string
          example: +39 000 1234567    
          pattern: "\\+[0-9]{2,2}\\s[0-9]{3,3}\\-[0-9]{7,7}" 
    StatoFlussoRendicontazione:
      description: Stato del flusso di rendicontazione
      example: Acquisito
      type: string
      enum:
        - Acquisito
        - Anomalo
        - Rifiutato          
    StatoRiscossione:
      description: Stato della riscossione
      example: RISCOSSA
      type: string
      enum:
        - RISCOSSA
        - INCASSATA
    TassonomiaAvviso:
      description: Macro categoria della pendenza Agid
      type: string
      enum:
        - Cartelle esattoriali
        - Diritti e concessioni
        - Imposte e tasse
        - IMU, TASI e altre tasse comunali
        - Ingressi a mostre e musei
        - Multe e sanzioni amministrative
        - Previdenza e infortuni
        - Servizi erogati dal comune
        - Servizi erogati da altri enti
        - Servizi scolastici
        - Tassa automobilistica
        - Ticket e prestazioni sanitarie
        - Trasporti, mobilità e parcheggi
      example: 
        Ticket e prestazioni sanitarie 
    TipoAutorizzazione:
      type: array
      items:
        type: string
        enum:
         - Lettura
         - Scrittura
      example:
        - Lettura
        - Scrittura 
    TipoPendenza:
      type: object
      required:
        - idTipoPendenza
        - descrizione
      properties:
        idTipoPendenza:
          type: string
          example: REFNIDO
        descrizione:
          type: string
          example: Refezione scolastica Asilo Nido         
    TipoRiscossione:
      description: > 
        Tipologia della voce riscossa
         * ENTRATA: Entrata in tesoreria
         * MBT: Marca da bollo telematica
         * ALTRO_INTERMEDIARIO: Entrata relativa a un intermediario esterno
         * ENTRATA_PA_NON_INTERMEDIATA: Entrata relativa ad un ente creditore non intermediato da GovPay
      type: string
      enum:
        - ENTRATA
        - MBT
        - ALTRO_INTERMEDIARIO
        - ENTRATA_PA_NON_INTERMEDIATA
    TipoServizio:
      type: string
      enum:
        - Anagrafica PagoPA
        - Anagrafica Creditore
        - Anagrafica Applicazioni
        - Anagrafica Ruoli
        - Pagamenti
        - Pendenze
        - Rendicontazioni e Incassi
        - Giornale degli Eventi
        - Configurazione e manutenzione
      example:
        Pendenze e Pagamenti             
    TipoSoggetto:
      description: >-
        tipologia di soggetto, se persona fisica (F) o giuridica
        (G)
      type: string
      enum:
        - G
        - F
      example: F
    VocePendenza:
      type: object
      required:
        - idVocePendenza
        - pendenza
      properties:
        indice:
          type: number
          description: indice di voce all'interno della pendenza
          example: 1
        idVocePendenza:
          type: string
          description: Identificativo della voce di pedenza nel gestionale proprietario
          example: abcdef12345_1   
        importo:
          type: number
          description: Importo della voce
          example: 10.01
        descrizione:
          type: string
          description: descrizione della voce di pagamento
          example: Sanzione CdS n. abc00000
          minLength: 1
          maxLength: 140  
        datiAllegati:
          type: object
          description: Dati applicativi allegati dal gestionale secondo un formato proprietario.  
        descrizioneCausaleRPT:
          type: string
          description: Testo libero per la causale versamento
          example: Sanzione CdS n. abc00000
          minLength: 1
          maxLength: 140
        contabilita:
          $ref: '#/components/schemas/Contabilita'
        pendenza:
          $ref: '#/components/schemas/Pendenza'
        dominio:
          $ref: '#/components/schemas/Dominio'
            
