openapi: 3.0.0
info:
  version: "1.4.0"
  title: GovPay - API Pendenze
  contact:
    name: GitHub Project Page
    url: 'https://github.com/link-it/GovPay/'
  license:
    name: GPL
    url: 'https://github.com/link-it/GovPay/blob/master/LICENSE'
servers:
  - url: ${it.govpay.apiurl}/govpay/backend/api/pendenze/rs/basic/v1/
tags:
  - name: Pendenze
    description: Consultazione delle posizioni debitorie
  - name: Pagamenti
    description: Realizzazione e consultazione dei pagamenti delle pendenze
  - name: Utenti
    description: Anagrafica degli Utenti
security:
  - basicAuth: []    
paths:
  '/pendenze':
    get:
      tags:
        - Pendenze
      operationId: findPendenze
      summary: Elenco delle pendenze
      description: Fornisce la lista delle pendenze filtrata ed ordinata.
      parameters:
        - in: query
          name: pagina
          description: Numero di pagina dei risultati
          required: false
          schema:
            type: integer
            default: 1
        - in: query
          name: risultatiPerPagina
          description: Numero massimo di risultati nella risposta
          required: false
          schema:
            type: integer
            default: 25
            maximum: 200
        - name: campi
          in: query
          description: >-
            csv dei campi da includere nella risposta (default tutti)
          required: false
          schema:
            type: string
            format: csv
        - name: ordinamento
          in: query
          description: >-
            csv dei campi su cui ordinare i risultati, preceduti da + o - per ascendente o discendente (default ascendente)
             * dataCaricamento
             * dataScadenza
             * dataValidita
             * stato
          required: false
          schema:
            type: string
            format: csv
            default: +dataCaricamento
        - name: dataDa
          in: query
          description: Inizio della finestra temporale di osservazione
          required: false
          schema:
            type: string  
            format: date-time     
        - name: dataA
          in: query
          description: Fine della finestra temporale di osservazione
          required: false
          schema:
            type: string  
            format: date-time
        - name: idDominio
          in: query
          description: filtro per dominio creditore
          required: false
          schema:
            type: string
        - name: idA2A
          in: query
          description: filtro per gestionale
          required: false
          schema:
            type: string
        - name: idDebitore
          in: query
          description: filtro per codice fiscale o p. iva del soggetoto debitore
          required: false
          schema:
            type: string
        - name: stato
          in: query
          description: filtro sullo stato della pendenza
          required: false
          schema:
            $ref: '#/components/schemas/statoPendenza'
        - in: query
          name: idPagamento
          description: Identificativo del pagamento
          required: false
          schema:
            type: string
        - $ref: '#/components/parameters/metadatiPaginazione'
        - $ref: '#/components/parameters/maxRisultati'
      responses:
        '200':
          description: Elenco delle pendenze che rispettano i filtri di ricerca
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/listaPaginata'
                  - type: object
                    required:
                      - risultati
                    properties:
                      risultati:
                        type: array
                        items:
                          $ref: '#/components/schemas/pendenzaIndex'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'      
  '/pendenze/{idA2A}/{idPendenza}':
    put:
      tags:
        - Pendenze
      summary: Creazione o aggiornamento di una pendenza
      description: >-
        Per ciascuna pendenza viene richiesto un identificativo (_idPendenza_)
        valido per il gestionale che ne effettua il caricamento (_idA2A_).
        L'operazione è idempotente rispetto a questo identificativo e nel caso
        venga eseguito il caricamento di una pendenza con un identificativo già
        presente nell'archivio di GovPay, questa sarà gestita come un
        aggiornamento. <br/> Ciascuna pendenza può
        essere composta da più voci fino ad un massimo di cinque, ciascuna
        avente un identificativo _idVocePendenza_ assegnato dal gestionale come
        riferimento interno. 
      operationId: addPendenza
      parameters:
        - in: path
          name: idA2A
          description: Identificativo del gestionale
          required: true
          schema:
            type: string
            pattern: '(^[a-zA-Z0-9\-_]{1,35}$)'
        - in: path
          name: idPendenza
          description: Identificativo della pendenza
          required: true
          schema:
            type: string
            pattern: '(^[a-zA-Z0-9\-_]{1,35}$)'
        - in: query
          name: stampaAvviso
          description: Indica se nella risposta deve essere inclusa la stampa dell'avviso in standard AgID
          required: false
          schema:
            type: boolean
            default: false
        - in: query
          name: avvisaturaDigitale
          description: Indica se la pendenza deve essere avvisata digitalmente
          required: false
          schema:
            type: boolean
            default: false
          deprecated: true
        - in: query
          name: modalitaAvvisaturaDigitale
          description: Modalita' di avvisatura scelta per le pendenza
          required: false
          schema:
            $ref: '#/components/schemas/modalitaAvvisaturaDigitale'
          deprecated: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/pendenzaPut'
      responses:
        '200':
          description: Pendenza aggiornata con successo
          content:
            application/json:
              schema:
                type: object
                required:
                  - idDominio
                  - numeroAvviso
                properties:
                  idDominio:
                    type: string
                    description: Identificativo del creditore dell'avviso
                    example: 01234567890
                  numeroAvviso:
                    type: string
                    description: Numero identificativo dell'avviso di pagamento
                    example: 00100000000000012
                  pdf:
                    type: string
                    format: base64
                    description: Stampa pdf dell'avviso
        '201':
          description: Pendenza creata con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/avviso'
        '400':
          $ref: '#/components/responses/400'
        '422':
          $ref: '#/components/responses/400'          
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
    patch:
      tags:
        - Pendenze
      summary: Aggiornamento di una pendenza
      operationId: updatePendenza      
      parameters:
        - in: path
          name: idA2A
          description: Identificativo del gestionale
          required: true
          schema:
            type: string
            pattern: '(^[a-zA-Z0-9\-_]{1,35}$)'
        - in: path
          name: idPendenza
          description: Identificativo della pendenza
          required: true
          schema:
            type: string
            pattern: '(^[a-zA-Z0-9\-_]{1,35}$)'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/patchOp'
              description: Lista di oggetti da aggiornare
      responses:
        '200':
          description: Pendenza aggiornata con successo
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'      
        '500':
          $ref: '#/components/responses/500'
    get:
      tags:
        - Pendenze
      operationId: getPendenza        
      summary: Dettaglio di una pendenza per identificativo
      description: Acquisisce il dettaglio di una pendenza, comprensivo dei dati di pagamento.
      parameters:
        - in: path
          name: idA2A
          description: Identificativo del gestionale
          required: true
          schema:
            type: string
            pattern: '(^[a-zA-Z0-9\-_]{1,35}$)'
        - in: path
          name: idPendenza
          description: Identificativo della pendenza
          required: true
          schema:
            type: string
            pattern: '(^[a-zA-Z0-9\-_]{1,35}$)'
      responses:
        '200':
          description: Informazioni dettagliate della pendenza
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pendenza'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
  '/rpp':
    get:  
      summary: Lista delle richieste di pagamento pendenza
      tags:
        - Pagamenti
      parameters:
        - in: query
          name: pagina
          description: Numero di pagina dei risultati
          required: false
          schema:
            type: integer
            default: 1
        - in: query
          name: risultatiPerPagina
          description: Numero massimo di risultati nella risposta
          required: false
          schema:
            type: integer
            default: 25
            maximum: 200
        - name: campi
          in: query
          description: >-
            csv dei campi da includere nella risposta (default tutti)
          required: false
          schema:
            type: string
            format: csv
        - name: ordinamento
          in: query
          description: >-
            csv dei campi su cui ordinare i risultati, preceduti da + o - per ascendente o discendente (default ascendente)
             * dataRichiesta
             * esito
          required: false
          schema:
            type: string
            format: csv
            default: +dataRichiesta
        - name: dataDa
          in: query
          description: Inizio della finestra temporale di osservazione
          required: false
          schema:
            type: string  
            format: date-time     
        - name: dataA
          in: query
          description: Fine della finestra temporale di osservazione
          required: false
          schema:
            type: string  
            format: date-time
        - in: query
          name: idDominio
          description: Codice fiscale del dominio beneficiario
          required: false
          schema:
            type: string
        - in: query
          name: iuv
          description: Identificativo univoco di versamento
          required: false
          schema:
            type: string
        - in: query
          name: ccp
          description: codice contesto pagamento
          required: false
          schema:
            type: string
        - in: query
          name: idA2A
          description: Codice del gestionale proprietario della pendenza
          required: false
          schema:
            type: string
        - in: query
          name: idPendenza
          description: Identrificativo della pendenza nel gestionale proprietario
          required: false
          schema:
            type: string
        - in: query
          name: esito
          description: esito della richiesta di pagamento
          required: false
          schema:
            $ref: '#/components/schemas/esitoRpt'
        - in: query
          name: idPagamento
          description: Identificativo del pagamento
          required: false
          schema:
            type: string
        - $ref: '#/components/parameters/metadatiPaginazione'
        - $ref: '#/components/parameters/maxRisultati'
      responses:
        '200':
          description: Lista delle richieste di pagamento pendenza che rispettano i criteri di ricerca
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/listaPaginata'
                  - type: object
                    required:
                      - risultati
                    properties:
                      risultati:
                        type: array
                        items:
                          $ref: '#/components/schemas/rppIndex'            
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'
  '/rpp/{idDominio}/{iuv}/{ccp}':
    get:
      summary: Dettaglio di una richiesta di pagamento pendenza
      tags:
        - Pagamenti
      parameters:
        - in: path
          name: idDominio
          description: Codice fiscale del dominio beneficiario
          required: true
          schema:
            type: string
            pattern: '(^([0-9]){11}$)'
        - in: path
          name: iuv
          description: Identificativo univoco di versamento
          required: true
          schema:
            type: string
        - in: path
          name: ccp
          description: Codice di contesto pagamento
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Dettaglio della richiesta di pagamento
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpp'            
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'           
  '/rpp/{idDominio}/{iuv}/{ccp}/rpt':
    get:
      summary: Acquisizione della richiesta di pagamento pagopa
      tags:
        - Pagamenti
      parameters:
        - in: path
          name: idDominio
          description: Codice fiscale del dominio beneficiario
          required: true
          schema:
            type: string
            pattern: '(^([0-9]){11}$)'
        - in: path
          name: iuv
          description: Identificativo univoco di versamento
          required: true
          schema:
            type: string
        - in: path
          name: ccp
          description: Codice di contesto pagamento
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Richiesta di pagamento
          content:
            application/xml:
              schema:
                type: string
                example: xml della richiesta di pagamento pagopa
            application/json:
              schema:
                type: string
                example: conversione json della richiesta di pagamento pagopa
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'                    
  '/rpp/{idDominio}/{iuv}/{ccp}/rt':
    get:
      summary: Acquisizione della ricevuta di pagamento
      tags:
        - Pagamenti
      parameters:
        - in: path
          name: idDominio
          description: Codice fiscale del dominio beneficiario
          required: true
          schema:
            type: string
            pattern: '(^([0-9]){11}$)'
        - in: path
          name: iuv
          description: Identificativo univoco di versamento
          required: true
          schema:
            type: string
        - in: path
          name: ccp
          description: Codice di contesto pagamento
          required: true
          schema:
            type: string
        - in: query
          name: visualizzaSoggettoDebitore
          description: Indica se inserire il soggetto debitore nel pdf della ricevuta
          schema:
            type: boolean
      responses:
        '200':
          description: Ricevuta di pagamento
          content:
            application/pdf:
              schema:
                type: string
                format: binary
                example: stampa della ricevuta
            application/xml:
              schema:
                type: string
                example: xml della ricevuta
            application/json:
              schema:
                type: string
                example: conversione json della ricevuta
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'             
  '/profilo':
    get:
      summary: Elenco delle acl associate all'utenza chiamante
      tags:
        - Utenti
      responses:
        '200':
          description: Elenco dei ruoli associati all'utenza chiamante
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/profilo'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '500':
          $ref: '#/components/responses/500'    
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  parameters:
    maxRisultati:
      name: maxRisultati
      in: query
      description: >-
            Indica se il servizio deve impostare o meno il limite sul calcolo del numero di risultati
      required: false
      schema:
        type: boolean
        default: true
      example: true
    metadatiPaginazione:
      name: metadatiPaginazione
      in: query
      description: >- 
              Indica se il servizio calcola e valorizza i dati di paginazione o meno
      required: false
      schema:
        type: boolean
        default: true
      example: true
  responses:
    '400':
      description: Richiesta non correttamente formata
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/faultBean'
          example:
            categoria: RICHIESTA
            codice: 00001
            descrizione: Messaggio di richiesta non valido
            dettaglio: Codice Avviso non conforme alle specifiche pagoPA
    '401':
      description: Richiesta non autenticata
    '403':
      description: Richiesta non autorizzata
    '404':
      description: Risorsa inesistente
    '500':
      description: Servizio non disponibile
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/faultBean'
          example:
            categoria: INTERNO
            codice: INTERNO
            descrizione: Servizio non disponibile
    '502':
      description: Rilevato errore con la piattaforma PagoPA
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/faultBean'
          example:
            categoria: PAGOPA
            codice: PPT_CANALE_IRRAGGIUNGIBILE
            descrizione: Errore di connessione verso il canale          
  schemas:
    faultBean:
      type: object
      required:
        - categoria
        - codice
        - descrizione
      properties:
        categoria:
          type: string
          description: >-
            Categoria dell'errore riscontrato:
             * `AUTORIZZAZIONE` - Operazione non autorizzata
             * `RICHIESTA` - Richiesta non valida
             * `OPERAZIONE` - Operazione non eseguibile
             * `PAGOPA` - Errore da PagoPA
             * `INTERNO` - Errore interno
          enum:
            - AUTORIZZAZIONE
            - RICHIESTA
            - OPERAZIONE
            - PAGOPA
            - INTERNO
        codice:
          type: string
          description: Codice di errore
        descrizione:
          type: string
          description: Descrizione dell'errore
        dettaglio:
          type: string
          description: Descrizione aggiuntiva  
    listaPaginata:
      type: object
      properties:
        numRisultati:
          type: number
          format: integer
          example: '100'
        numPagine:
          type: number
          format: integer
          example: '4'
        risultatiPerPagina:
          type: number
          format: integer
          example: '25'
        pagina:
          type: number
          format: integer
          example: '1'
        prossimiRisultati:
          type: string
          format: integer
          example: '/risorsa?pagina=2'    
    soggetto:
      description: dati anagrafici di un versante o pagatore.
      type: object
      required:
        - tipo
        - identificativo
      properties:
        tipo:
          description: >-
            tipologia di soggetto, se persona fisica (F) o giuridica
            (G)
          type: string
          enum:
            - G
            - F
          example: F
        identificativo:
          description: codice fiscale o partita iva del soggetto
          type: string
          example: RSSMRA30A01H501I
        anagrafica:
          description: nome e cognome o altra ragione sociale del soggetto
          type: string
          example: Mario Rossi
        indirizzo:
          type: string
          example: Piazza della Vittoria
        civico:
          type: string
          example: 10/A
        cap:
          type: string
          example: 0
        localita:
          type: string
          example: Roma
        provincia:
          type: string
          example: Roma
        nazione:
          type: string
          example: IT
        email:
          type: string
          example: mario.rossi@host.eu
        cellulare:
          type: string
          example: 0039000123456789    
    segnalazione:
      type: object
      required:
        - codice
        - descrizione
      properties:
        data:
          type: string
          format: date
          example: '2018-12-31'
        codice:
          type: string
          example: '0013'
        descrizione:
          type: string   
          example: 'Pagamento rendicontato senza RPT'
        dettaglio:
          type: string
          example: 'Acquisita rendicontazione senza RPT nel flusso ABC-1234-DEFG'  
    avviso:
      type: object
      required:
        - stato
      properties:
        stato:
          description: Stato dell'avviso
          example: Non pagato
          type: string
          enum:
            - Pagato
            - Non pagato
            - Scaduto
            - Annullato
        importo:
          type: number
          description: Importo della pendenza associata all'avviso.
          example: 10.01
        idDominio:
          type: string
          description: Identificativo del creditore dell'avviso
          example: 01234567890
        numeroAvviso:
          type: string
          description: Numero identificativo dell'avviso di pagamento
          example: 00100000000000012
        dataValidita:
          type: string
          format: date
          description: Data di validita dei dati dell'avviso, decorsa la quale l'importo può subire variazioni.
          example: '2019-12-31'
        dataScadenza:
          type: string
          format: date
          description: Data di scadenza dell'avviso, decorsa la quale non è più pagabile.
          example: '2020-12-31'
        descrizione:
          type: string
          description: Descrizione da inserire nell'avviso di pagamento
          example: 'Sanzione CdS n. abc00000'
        tassonomiaAvviso:
          $ref: '#/components/schemas/tassonomiaAvviso'
        qrcode:
          type: string
          description: Testo da codificare nel qr-code dell'avviso
        barcode:
          type: string
          description: Testo da codificare nel bar-code dell'avviso   
        pdf:
          type: string
          format: base64
          description: Stampa pdf dell'avviso
    tassonomiaAvviso:
      description: Macro categoria della pendenza Agid
      type: string
      enum:
        - Cartelle esattoriali
        - Diritti e concessioni
        - Imposte e tasse
        - IMU, TASI e altre tasse comunali
        - Ingressi a mostre e musei
        - Multe e sanzioni amministrative
        - Previdenza e infortuni
        - Servizi erogati dal comune
        - Servizi erogati da altri enti
        - Servizi scolastici
        - Tassa automobilistica
        - Ticket e prestazioni sanitarie
        - Trasporti, mobilità e parcheggi
      example: 
        Ticket e prestazioni sanitarie
    dominioPost:
      type: object
      required:
       - ragioneSociale
       - gln
       - stazione
       - abilitato
      properties:
        ragioneSociale:
          type: string
          description: Ragione sociale del beneficiario
          example: Ente Creditore
        indirizzo:
          type: string
          description: Indirizzo del beneficiario
          example: Corso Italia
        civico:
          type: string
          description: Numero civico del beneficiario
          example: 1A
        cap:
          type: string
          description: Codice avviamento postale del beneficiario
          example: 00000
        localita:
          type: string
          description: Località del beneficiario
          example: Roma
        provincia:
          type: string
          description: Provincia del beneficiario
          example: Roma
        nazione:
          type: string
          description: Nazione del beneficiario
          example: IT
        email:
          type: string
          description: Posta elettronica ordinaria del beneficiario
          example: peo@creditore.it  
        pec:
          type: string
          description: Posta elettronica certificata del beneficiario
          example: pec@creditore.it  
        tel:
          type: string
          description: Numero di telefono dell'help desk del beneficiario
          example: 021234567890  
        fax:
          type: string
          description: Numero di fax dell'help desk del beneficiario
          example: 021234567890  
        web:
          type: string
          description: Url del sito web
          example: http://www.comune.it/
        gln:
          type: string
          description: Global location number del beneficiario
          example: 0011223344556
        cbill:
          type: string
          description: codice cbill del beneficiario
          example: 12345
        iuvPrefix:
          type: string
          description: Prefisso negli IUV generati da GovPay
          example: '%(yyyy)%(a)'
        stazione:
          type: string
          description: Codice stazione PagoPA che intermedia il beneficiario
          example: 01234567890_01
        auxDigit:
          type: string
          description: Valore della prima cifra dei Numero Avviso generati da GovPay
          example: 0
        segregationCode:
          type: string
          description: Codice di segregazione utilizzato in caso di beneficiario pluri-intermediato (auxDigit = 3)
          example: 88
        logo:
          type: string
          description: Base64 del logo del beneficiario
          example: /9j/4AA...base64...FFFFABRRRQB/9k=
        abilitato:
          type: boolean
          description: Indicazione se il creditore è abilitato ad operare sulla piattaforma
          example: 'true'
    dominioIndex:
      type: object
      allOf:
        - type: object
          required:
            - idDominio
          properties:
            idDominio:
              type: string
              description: Codice fiscale del beneficiario
              example: 01234567890
        - $ref: '#/components/schemas/dominioPost'
        - type: object
          required:
            - unitaOperative
            - contiAccredito
            - entrate
          properties:
            unitaOperative:
              type: string
              description: Url alle unità operative censite per il dominio
              example: /domini/01234567890/unitaOperative
            contiAccredito:
              type: string
              description: Conti di accredito censiti per il dominio beneficiario
              example: /domini/01234567890/contiAccredito
            entrate:
              type: string
              description: Tipologie di entrata censite per il dominio beneficiario
              example: /domini/01234567890/entrate               
    unitaOperativaPost:
      type: object
      required: 
        - ragioneSociale
      properties:
        ragioneSociale:
          type: string
          description: Ragione sociale dell'unita
          example: Ufficio due
        indirizzo:
          type: string
          description: Indirizzo dell'unita
          example: Borgo stretto
        civico:
          type: string
          description: Numero civico dell'unita
          example: 55bis
        cap:
          type: string
          description: Codice avviamento postale dell'unita
          example: 99999
        localita:
          type: string
          description: Località dell'unita
          example: Milano
        provincia:
          type: string
          description: Provincia del beneficiario
          example: Roma
        nazione:
          type: string
          description: Nazione del beneficiario
          example: IT
        email:
          type: string
          description: Posta elettronica ordinaria del beneficiario
          example: peo@creditore.it  
        pec:
          type: string
          description: Posta elettronica certificata del beneficiario
          example: pec@creditore.it  
        tel:
          type: string
          description: Numero di telefono dell'help desk del beneficiario
          example: 021234567890  
        fax:
          type: string
          description: Numero di fax dell'help desk del beneficiario
          example: 021234567890           
        web:
          type: string
          description: Url del sito web
          example: http://www.comune.it/
        area:
          type: string
          description: Nome dell'area di competenza dell'unita' operativa
          example: Affari generali e istituzionali  
        abilitato:
          type: boolean
          description: Indica lo stato di abilitazione
          example: true
    unitaOperativa:
      type: object
      allOf:
        - type: object
          required:
           - idUnita
          properties:
            idUnita:
              type: string
              description: Codice fiscale dell'unita
              example: 01234567890
        - $ref: '#/components/schemas/unitaOperativaPost'
    tipoEntrataPost:
      type: object
      required: 
        - descrizione
        - tipoContabilita
        - codiceContabilita
      properties:
        descrizione:
          type: string
          example: Imposta municipale urbana
        tipoContabilita:
          $ref: '#/components/schemas/tipoContabilita'
        codiceContabilita:
          description: Codifica del capitolo di bilancio
          type: string
          example: 3321
    tipoEntrata:
      type: object
      allOf:
        - type: object
          required:
           - idEntrata
          properties:
            idEntrata:
              type: string
              example: IMU
        - $ref: '#/components/schemas/tipoEntrataPost'
    tipoContabilita:
      description: Tipologia di codifica del capitolo di bilancio
      type: string
      enum:
        - ENTRATA
        - SPECIALE
        - SIOPE
        - ALTRO
      example: SIOPE
    pendenzaBase:
      type: object
      required:
        - soggettoPagatore
        - importo
        - causale
      properties:
        nome:
          type: string
          description: Nome della pendenza da visualizzare sui portali di pagamento e console di gestione.
          example: 'Immatricolazione AA 2017/2018'
        causale:
          type: string
          description: Descrizione da inserire nell'avviso di pagamento
          example: 'Sanzione CdS n. abc00000'
        soggettoPagatore:
          $ref: '#/components/schemas/soggetto'
        importo:
          type: number
          description: Importo della pendenza. Deve corrispondere alla somma delle singole voci.
          example: 10.01
        numeroAvviso:
          type: string
          description: Identificativo univoco versamento, assegnato se pagabile da psp
          example: 123456789012345678
        dataCaricamento:
          type: string
          format: date
          description: Data di emissione della pendenza
          example: '2010-12-31'
        dataValidita:
          type: string
          format: date
          description: Data di validita dei dati della pendenza, decorsa la quale la pendenza può subire variazioni.
          example: '2019-12-31'
        dataScadenza:
          type: string
          format: date
          description: Data di scadenza della pendenza, decorsa la quale non è più pagabile.
          example: '2020-12-31'
        annoRiferimento:
          type: number
          description: Anno di riferimento della pendenza
          example: 2020
        cartellaPagamento:
          type: string
          description: Identificativo della cartella di pagamento a cui afferisce la pendenza
          example: ABC00000001
        datiAllegati:
          type: object
          description: Dati applicativi allegati dal gestionale secondo un formato proprietario.          
        tassonomia:
          type: string
          description: Macro categoria della pendenza secondo la classificazione del creditore
          example: Sanzioni
        tassonomiaAvviso:
          $ref: '#/components/schemas/tassonomiaAvviso'
    pendenzaPut:
      type: object
      allOf:
        - type: object
          required:
            - idDominio
          properties:
            idDominio:
              type: string
              description: Identificativo del dominio creditore
              example: 1234567890
              pattern: '(^([0-9]){11}$)'
            idUnitaOperativa:
              type: string
              description: Identificativo dell'unita' operativa
              example: UO33132
              pattern: '(^[a-zA-Z0-9\-_]{1,35}$)'
        - $ref: '#/components/schemas/pendenzaBase'    
        - type: object
          required:
            - voci
          properties:   
            voci:
              type: array
              minItems: 1
              maxItems: 5
              items:
                $ref: '#/components/schemas/vocePendenza'
    pendenzaIndex:
      type: object
      allOf:
        - type: object
          required:
            - idA2A
            - idPendenza
            - dominio
            - stato
          properties:
            idA2A:
              type: string
              description: Identificativo del gestionale responsabile della pendenza
              example: A2A-12345
            idPendenza:
              type: string
              description: Identificativo della pendenza nel gestionale responsabile
              example: abcdef12345
            dominio:
              $ref: '#/components/schemas/dominioIndex'
            unitaOperativa:
              $ref: '#/components/schemas/unitaOperativa'
            stato:
              $ref: '#/components/schemas/statoPendenza'
            segnalazioni:
              type: array
              items: 
                $ref: '#/components/schemas/segnalazione'          
        - $ref: '#/components/schemas/pendenzaBase'   
        - type: object
          required:
            - rpp
          properties:
            rpp:
              type: string
              description: Url per l'elenco delle rpp emesse per la pendenza
              example: '/rpp?idPendenza=idA2A=A2A-12345&abcdef12345'
    pendenza:
      type: object
      allOf:
        - type: object
          required:
            - idA2A
            - idPendenza
            - dominio
            - stato
          properties:
            idA2A:
              type: string
              description: Identificativo del gestionale responsabile della pendenza
              example: A2A-12345
            idPendenza:
              type: string
              description: Identificativo della pendenza nel gestionale responsabile
              example: abcdef12345
            dominio:
              $ref: '#/components/schemas/dominioIndex'
            unitaOperativa:
              $ref: '#/components/schemas/unitaOperativa'
            stato:
              $ref: '#/components/schemas/statoPendenza'
            segnalazioni:
              type: array
              items: 
                $ref: '#/components/schemas/segnalazione'          
        - $ref: '#/components/schemas/pendenzaBase'   
        - type: object
          required:
            - voci
            - rpp
          properties:
            voci:
              type: array
              minItems: 1
              maxItems: 5
              items:
                $ref: '#/components/schemas/vocePendenza'
            rpp:
              type: array
              items:
                $ref: '#/components/schemas/rppIndex'
    vocePendenza:
      allOf:
        - type: object
          required:
            - idVocePendenza
            - importo
            - descrizione
            - stato
          properties:
            indice:
              type: number
              description: indice di voce all'interno della pendenza
              example: 1
            idVocePendenza:
              type: string
              description: Identificativo della voce di pedenza nel gestionale proprietario
              example: abcdef12345_1
            importo:
              type: number
              description: Importo della voce
              example: 10.01
            descrizione:
              type: string
              description: descrizione della voce di pagamento
              example: Sanzione CdS n. abc00000
            stato:
              type: string
              description: Stato della voce di pagamento
              enum:
                - Eseguito
                - Non eseguito
                - Anomalo
            datiAllegati:
              type: object
              description: Dati applicativi allegati dal gestionale secondo un formato proprietario.
            descrizioneCausaleRPT:
              type: string
              description: Testo libero per la causale versamento
              example: Sanzione CdS n. abc00000
              minLength: 1
              maxLength: 140
        - oneOf:
            - description: Definisce i dettagli di incasso tramite riferimento in anagrafica GovPay.
              type: object
              required:
                - codEntrata
              properties:
                codEntrata:
                  type: string
                  pattern: '(^[a-zA-Z0-9\-_\.]{1,35}$)'
            - description: Definisce i dettagli di incasso.
              type: object
              required:
                - ibanAccredito
                - tipoContabilita
                - codiceContabilita
              properties:
                ibanAccredito:
                  type: string
                  example: IT60X0542811101000000123456
                ibanAppoggio:
                  type: string
                  example: IT60X0542811101000000123456
                tipoContabilita:
                  $ref: '#/components/schemas/tipoContabilita'
                codiceContabilita:
                  description: Codifica del capitolo di bilancio
                  type: string
                  example: 3321
            - description: Definisce i dati di un bollo telematico
              type: object
              required:
                - tipoBollo
                - hashDocumento
                - provinciaResidenza
              properties:
                tipoBollo:
                  description: Tipologia di Bollo digitale
                  type: string
                  enum:
                    - Imposta di bollo
                hashDocumento:
                  description: Digest in base64 del documento informatico associato alla marca da bollo
                  type: string
                provinciaResidenza:
                  description: Sigla automobilistica della provincia di residenza del soggetto pagatore
                  type: string
    statoPendenza:
      example: NON_ESEGUITA
      type: string
      enum:
        - ESEGUITA
        - NON_ESEGUITA
        - ESEGUITA_PARZIALE
        - ANNULLATA
        - SCADUTA
      description: >-
        Stato della pendenza: 
         * ESEGUITA: Pagata
         * NON_ESEGUITA: Da pagare
         * ESEGUITA_PARZIALE: Pagata parzialmente
         * ANNULLATA: Annullata
         * SCADUTA: Scaduta
    rppIndex:
      type: object
      required: 
        - stato
        - rpt
      properties:
        stato:
          type: string
          description: Stato della richiesta di pagamento sulla piattaforma PagoPA.
          example: RT_ACCETTATA_PA
        dettaglioStato:
          type: string
          description: >-
            Dettaglio fornito dal Nodo dei Pagamenti sullo stato della
            richiesta.
        segnalazioni:
          type: array
          items: 
            $ref: '#/components/schemas/segnalazione'
        rpt:
          type: object
          description: "Rpt inviata a PagoPa. {http://www.digitpa.gov.it/schemas/2011/Pagamenti/} ctRichiestaPagamentoTelematico"
        rt:
          type: object
          description: "Rt inviata da PagoPa. {http://www.digitpa.gov.it/schemas/2011/Pagamenti/} ctRicevutaTelematica"  
        pendenza:
          type: string
          description: Url al dettaglio della pendenza
          example: '/pendenze/A2A-12345/abcdef12345'
    rpp:
      type: object
      required: 
        - stato
        - rpt
      properties:
        stato:
          type: string
          description: Stato della richiesta di pagamento sulla piattaforma PagoPA.
          example: RT_ACCETTATA_PA
        dettaglioStato:
          type: string
          description: >-
            Dettaglio fornito dal Nodo dei Pagamenti sullo stato della
            richiesta.
        segnalazioni:
          type: array
          items: 
            $ref: '#/components/schemas/segnalazione'
        rpt:
          type: object
          description: "Rpt inviata a PagoPa. {http://www.digitpa.gov.it/schemas/2011/Pagamenti/} ctRichiestaPagamentoTelematico"
        rt:
          type: object
          description: "Rt inviata da PagoPa. {http://www.digitpa.gov.it/schemas/2011/Pagamenti/} ctRicevutaTelematica"  
        pendenza:
          $ref: '#/components/schemas/pendenzaIndex'         
    esitoRpt:
      example: ESEGUITO
      type: string
      enum:
        - IN_CORSO
        - RIFIUTATO
        - ESEGUITO
        - NON_ESEGUITO
        - ESEGUITO_PARZIALE
        - DECORRENZA
        - DECORENNZA_PARZIALE
      description: > 
        Esito della richiesta di pagamento:
         * IN_CORSO: Pagamento in corso
         * RIFIUTATO: Pagamento rifiutato
         * ESEGUITO: Pagamento eseguito
         * NON_ESEGUITO: Pagamento non eseguito
         * ESEGUITO_PARZIALE: Pagamento parzialmente eseguito
         * DECORRENZA: Decorrenza termini
         * DECORRENZA_PARZIALE: Decorrenza termini parziale
    aclPost:
      type: object
      required:
        - servizio
        - autorizzazioni
      properties:
        ruolo:
          type: string
          description: ruolo a cui si applica l'acl
          example: Operatore
        principal:
          type: string
          description: principal a cui si applica l'acl
          example: user001
        servizio:
          type: string
          description: >- 
            Servizio oggetto dell'autorizzazione
             * Anagrafica PagoPA
             * Anagrafica Creditore
             * Anagrafica Applicazioni
             * Anagrafica Ruoli
             * Pendenze e Pagamenti
             * Pendenze e Pagamenti propri 
             * Rendicontazioni e Incassi
             * Giornale degli Eventi
             * Statistiche
             * Configurazione e Manutenzione
          example:
            Pendenze e Pagamenti
        autorizzazioni:
          type: array
          items:
            type: string
            enum:
             - Lettura
             - Scrittura
             - Esecuzione
          example:
            - Lettura
            - Scrittura
    patchOp:
      type: object
      required: 
        - op
        - path
        - value
      properties:
        op:
          type: string
          enum:
            - ADD
            - DELETE
            - REPLACE
          description: Operazione da eseguire
          example: "ADD"
        path:
          type: string
          description: path dell'oggetto dell'operazione
          example: "domini"
        value:
          type: object
          description: valore del'oggetto dell'operazione
          example: "01234567890"            
    profilo:
      type: object
      required: 
        - nome
        - domini
        - entrate
        - acl
      properties:
        nome:
          type: string
          description: Nome dell'utenza
        domini:
          type: array
          description: domini su cui e' abilitato ad operare
          items: 
            $ref: '#/components/schemas/dominioIndex'
        entrate:
          type: array
          description: entrate su cui e' abilitato ad operare
          items: 
            $ref: '#/components/schemas/tipoEntrata'
        acl:
          type: array
          items:
            $ref: '#/components/schemas/aclPost'
    modalitaAvvisaturaDigitale:
      example: ASINCRONA
      type: string
      enum:
        - ASINCRONA
        - SINCRONA
